from django_backend.models import CompanyTriggerSegment


CATEGORY_MAPPING = {
    "Sales": "SA",
    "Marketing": "MA",
    "Operations / Admin": "OA",
    "Tech": "TE",
    "Product / Design": "PD",
    "All": "AL"
}


SUB_CATEGORIES_MAPPING = {
    "Account Executive/Account Manager AE/AM": "AE",
    "Sales Manager": "SM",
    "SDR/BDR": "SB",
    "Field Sales": "FS",
    "Digital Marketing": "DM",
    "Content Specialist": "CS",
    "Email Marketing Specialist": "EM",
    "Event Marketing": "EV",
    "Customer Success Manager": "CSM",
    "Customer Support": "CSP",
    "Field Support": "FSP",
    "Logistics": "LO",
    "Legal and Compliance": "LC",
    "Recruiting Operations": "RO",
    "Software Engineering": "SE",
    "Artificial Intelligence": "AI",
    "Dev Ops": "DO",
    "QA Quality Assurance": "QA",
    "Product Management": "PM",
    "Program Management": "PGM",
    "Product Operations": "PO",
    "Graphic Designer": "GD",
    "UI Design": "UID"
}




SUB_CATEGORY_CHOICES = {
    # Sales
    CompanyTriggerSegment.ACCOUNT_EXECUTIVE: [
        "account executive",
        "account manager",
    ],
    CompanyTriggerSegment.SALES_MANAGER: [
        "sales",
    ],
    CompanyTriggerSegment.SDR_BDR: [
        "sales development",
        "business development",
        "lead generation",
    ],
    CompanyTriggerSegment.FIELD_SALES: [
        "field sales",
        "territory sales",
        "outside sales"
    ],
    CompanyTriggerSegment.DIGITAL_MARKETING: [
        "digital marketing",
        "seo",
        "social media"
    ],
    CompanyTriggerSegment.CONTENT_SPECIALIST: [
        "content writer",
        "copywriter",
    ],
    CompanyTriggerSegment.EMAIL_MARKETING: [
        "email marketing",
        "crm",
        "campaign manager"
    ],
    CompanyTriggerSegment.EVENT_MARKETING: [
        "event marketing",
        "trade show",
        "events",
        "event promotions"
    ],

    # Operations / Admin
    CompanyTriggerSegment.CUSTOMER_SUCCESS: [
        "customer success",
        "technical support",
        "client relations"
    ],
    CompanyTriggerSegment.LOGISTICS: [
        "logistics",
        "field support",
        "supply chain"
    ],
    CompanyTriggerSegment.LEGAL_COMPLIANCE: [
        "compliance",
        "legal",
        "risk"
    ],
    CompanyTriggerSegment.RECRUITING_OPERATIONS: [
        "hr",
        "hiring",
        "talent acquisition",
        "recruiting operations"
    ],

    # Tech
    CompanyTriggerSegment.SOFTWARE_ENGINEERING: [
        "software engineer",
        "developer",
        "backend",
        "frontend"
    ],

    CompanyTriggerSegment.ARTIFICIAL_INTELLIGENCE: [
        "machine learning",
        "ai"
    ],
    CompanyTriggerSegment.DEV_OPS: [
        "devops",
        "quality assurance",
    ],

    # Product / Design
    CompanyTriggerSegment.PRODUCT_MANAGEMENT: [
        "product",
        "program"
    ],
    CompanyTriggerSegment.GRAPHIC_DESIGNER: [
        "graphic",
        "ui/ux",
        "visual designer"
    ],
}


CATEGORIES_MAP =  {
    "SA": ["AE", "SM", "SB", "FS"],
    "MA": ["DM", "CS", "EM", "EV"],
    "OA": ["CSM", "CSP", "FSP", "LO", "LC", "RO"],
    "TE": ["SE", "AI", "DO", "QA"],
    "PD": ["PM", "PGM", "GD", "UID"],
    "AL": []
}



LINKEDIN_INDUSTRY_LABELS_IDS = {'accommodation-services': 2190,
 'food-and-beverage-services': 34,
 'bars-taverns-and-nightclubs': 2217,
 'caterers': 2212,
 'mobile-food-services': 2214,
 'restaurants': 32,
 'hospitality': 31,
 'bed-and-breakfasts-hostels-homestays': 2197,
 'hotels-and-motels': 2194,
 'administrative-and-support-services': 1912,
 'collection-agencies': 1938,
 'events-services': 110,
 'facilities-services': 122,
 'janitorial-services': 1965,
 'landscaping-services': 2934,
 'fundraising': 101,
 'office-administration': 1916,
 'security-and-investigations': 121,
 'security-guards-and-patrol-services': 1956,
 'security-systems-services': 1958,
 'staffing-and-recruiting': 104,
 'executive-search-services': 1923,
 'temporary-help-services': 1925,
 'telephone-call-centers': 1931,
 'translation-and-localization': 108,
 'travel-arrangements': 30,
 'writing-and-editing': 103,
 'construction': 48,
 'building-construction': 406,
 'nonresidential-building-construction': 413,
 'residential-building-construction': 408,
 'civil-engineering': 51,
 'highway-street-and-bridge-construction': 431,
 'subdivision-of-land': 428,
 'utility-system-construction': 419,
 'specialty-trade-contractors': 435,
 'building-equipment-contractors': 453,
 'building-finishing-contractors': 460,
 'building-structure-and-exterior-contractors': 436,
 'consumer-services': 91,
 'civic-and-social-organizations': 90,
 'industry-associations': 1909,
 'political-organizations': 107,
 'professional-organizations': 1911,
 'household-services': 2318,
 'non-profit-organizations': 100,
 'personal-and-laundry-services': 2258,
 'laundry-and-drycleaning-services': 2272,
 'personal-care-services': 2259,
 'pet-services': 2282,
 'philanthropic-fundraising-services': 131,
 'religious-institutions': 89,
 'repair-and-maintenance': 2225,
 'commercial-and-industrial-machinery-maintenance': 2247,
 'electronic-and-precision-equipment-maintenance': 2240,
 'footwear-and-leather-goods-repair': 2255,
 'reupholstery-and-furniture-repair': 2253,
 'vehicle-repair-and-maintenance': 2226,
 'education': 1999,
 'e-learning-providers': 132,
 'higher-education': 68,
 'primary-and-secondary-education': 67,
 'professional-training-and-coaching': 105,
 'technical-and-vocational-training': 2018,
 'cosmetology-and-barber-schools': 2019,
 'fine-arts-schools': 2025,
 'flight-training': 2020,
 'language-schools': 2029,
 'secretarial-schools': 2012,
 'sports-and-recreation-instruction': 2027,
 'entertainment-providers': 28,
 'artists-and-writers': 38,
 'museums-historical-sites-and-zoos': 37,
 'historical-sites': 2161,
 'museums': 2159,
 'zoos-and-botanical-gardens': 2163,
 'musicians': 115,
 'performing-arts-and-spectator-sports': 2130,
 'circuses-and-magic-shows': 2139,
 'dance-companies': 2135,
 'performing-arts': 39,
 'spectator-sports': 33,
 'racetracks': 2143,
 'sports-teams-and-clubs': 2142,
 'theater-companies': 2133,
 'recreational-facilities': 40,
 'amusement-parks-and-arcades': 2167,
 'gambling-facilities-and-casinos': 29,
 'golf-courses-and-country-clubs': 2179,
 'skiing-facilities': 2181,
 'wellness-and-fitness-services': 124,
 'financial-services': 43,
 'capital-markets': 129,
 'investment-advice': 1720,
 'investment-banking': 45,
 'investment-management': 46,
 'securities-and-commodity-exchanges': 1713,
 'venture-capital-and-private-equity-principals': 106,
 'credit-intermediation': 1673,
 'banking': 41,
 'international-trade-and-development': 141,
 'loan-brokers': 1696,
 'savings-institutions': 1678,
 'funds-and-trusts': 1742,
 'insurance-and-employee-benefit-funds': 1743,
 'pension-funds': 1745,
 'trusts-and-estates': 1750,
 'insurance': 42,
 'claims-adjusting-actuarial-services': 1738,
 'insurance-agencies-and-brokerages': 1737,
 'insurance-carriers': 1725,
 'government-administration': 75,
 'administration-of-justice': 73,
 'correctional-institutions': 3068,
 'courts-of-law': 3065,
 'fire-protection': 3070,
 'law-enforcement': 77,
 'public-safety': 78,
 'economic-programs': 2375,
 'transportation-programs': 3085,
 'utilities-administration': 3086,
 'environmental-quality-programs': 388,
 'air-water-and-waste-program-management': 2366,
 'conservation-programs': 2368,
 'health-and-human-services': 2353,
 'education-administration-programs': 69,
 'public-assistance-programs': 2360,
 'public-health': 2358,
 'housing-and-community-development': 2369,
 'community-development-and-urban-planning': 2374,
 'housing-programs': 3081,
 'military-and-international-affairs': 2391,
 'armed-forces': 71,
 'international-affairs': 74,
 'public-policy-offices': 79,
 'executive-offices': 76,
 'legislative-offices': 72,
 'space-research-and-technology': 3089,
 'holding-companies': 1905,
 'hospitals-and-health-care': 14,
 'community-services': 2115,
 'services-for-the-elderly-and-disabled': 2112,
 'hospitals': 2081,
 'individual-and-family-services': 88,
 'child-day-care-services': 2128,
 'emergency-and-relief-services': 2122,
 'vocational-rehabilitation-services': 2125,
 'medical-practices': 13,
 'alternative-medicine': 125,
 'ambulance-services': 2077,
 'chiropractors': 2048,
 'dentists': 2045,
 'family-planning-centers': 2060,
 'home-health-care-services': 2074,
 'medical-and-diagnostic-laboratories': 2069,
 'mental-health-care': 139,
 'optometrists': 2050,
 'outpatient-care-centers': 2063,
 'physical-occupational-and-speech-therapists': 2054,
 'physicians': 2040,
 'nursing-homes-and-residential-care-facilities': 2091,
 'manufacturing': 25,
 'apparel-manufacturing': 598,
 'fashion-accessories-manufacturing': 615,
 'appliances-electrical-and-electronics-manufacturing': 112,
 'electric-lighting-equipment-manufacturing': 998,
 'electrical-equipment-manufacturing': 2468,
 'fuel-cell-manufacturing': 3255,
 'household-appliance-manufacturing': 1005,
 'chemical-manufacturing': 54,
 'agricultural-chemical-manufacturing': 709,
 'artificial-rubber-and-synthetic-fiber-manufacturing': 703,
 'chemical-raw-materials-manufacturing': 690,
 'paint-coating-and-adhesive-manufacturing': 722,
 'personal-care-product-manufacturing': 18,
 'pharmaceutical-manufacturing': 15,
 'soap-and-cleaning-product-manufacturing': 727,
 'climate-technology-product-manufacturing': 3251,
 'computers-and-electronics-manufacturing': 24,
 'audio-and-video-equipment-manufacturing': 973,
 'communications-equipment-manufacturing': 964,
 'computer-hardware-manufacturing': 3,
 'accessible-hardware-manufacturing': 3245,
 'magnetic-and-optical-media-manufacturing': 994,
 'measuring-and-control-instrument-manufacturing': 983,
 'smart-meter-manufacturing': 3254,
 'semiconductor-manufacturing': 7,
 'renewable-energy-semiconductor-manufacturing': 144,
 'fabricated-metal-products': 840,
 'architectural-and-structural-metal-manufacturing': 852,
 'boilers-tanks-and-shipping-container-manufacturing': 861,
 'construction-hardware-manufacturing': 871,
 'cutlery-and-handtool-manufacturing': 849,
 'metal-treatments': 883,
 'metal-valve-ball-and-roller-manufacturing': 887,
 'spring-and-wire-product-manufacturing': 873,
 'turned-products-and-fastener-manufacturing': 876,
 'food-and-beverage-manufacturing': 23,
 'breweries': 562,
 'distilleries': 564,
 'wineries': 2500,
 'animal-feed-manufacturing': 481,
 'baked-goods-manufacturing': 529,
 'beverage-manufacturing': 142,
 'dairy-product-manufacturing': 65,
 'fruit-and-vegetable-preserves-manufacturing': 504,
 'meat-products-manufacturing': 521,
 'seafood-product-manufacturing': 528,
 'sugar-and-confectionery-product-manufacturing': 495,
 'furniture-and-home-furnishings-manufacturing': 26,
 'household-and-institutional-furniture-manufacturing': 1080,
 'mattress-and-blinds-manufacturing': 1095,
 'office-furniture-and-fixtures-manufacturing': 1090,
 'glass-ceramics-and-concrete-manufacturing': 145,
 'abrasives-and-nonmetallic-minerals-manufacturing': 799,
 'clay-and-refractory-products-manufacturing': 773,
 'glass-product-manufacturing': 779,
 'lime-and-gypsum-products-manufacturing': 794,
 'leather-product-manufacturing': 616,
 'footwear-manufacturing': 622,
 'women’s-handbag-manufacturing': 625,
 'machinery-manufacturing': 55,
 'agriculture-construction-mining-machinery-manufacturing': 901,
 'automation-machinery-manufacturing': 147,
 'robot-manufacturing': 3247,
 'commercial-and-service-industry-machinery-manufacturing': 918,
 'engines-and-power-transmission-equipment-manufacturing': 935,
 'renewable-energy-equipment-manufacturing': 3241,
 'hvac-and-refrigeration-equipment-manufacturing': 923,
 'industrial-machinery-manufacturing': 135,
 'metalworking-machinery-manufacturing': 928,
 'medical-equipment-manufacturing': 17,
 'oil-and-coal-product-manufacturing': 679,
 'paper-and-forest-product-manufacturing': 61,
 'plastics-and-rubber-product-manufacturing': 743,
 'packaging-and-containers-manufacturing': 146,
 'plastics-manufacturing': 117,
 'rubber-products-manufacturing': 763,
 'primary-metal-manufacturing': 807,
 'printing-services': 83,
 'sporting-goods-manufacturing': 20,
 'textile-manufacturing': 60,
 'tobacco-manufacturing': 21,
 'transportation-equipment-manufacturing': 1029,
 'aviation-and-aerospace-component-manufacturing': 52,
 'defense-and-space-manufacturing': 1,
 'motor-vehicle-manufacturing': 53,
 'alternative-fuel-vehicle-manufacturing': 3253,
 'motor-vehicle-parts-manufacturing': 1042,
 'railroad-equipment-manufacturing': 62,
 'shipbuilding': 58,
 'wood-product-manufacturing': 784,
 'professional-services': 1810,
 'accounting': 47,
 'advertising-services': 80,
 'government-relations-services': 148,
 'public-relations-and-communications-services': 98,
 'market-research': 97,
 'architecture-and-planning': 50,
 'accessible-architecture-and-design': 3246,
 'business-consulting-and-services': 11,
 'environmental-services': 86,
 'human-resources-services': 137,
 'marketing-services': 1862,
 'operations-consulting': 2401,
 'outsourcing-and-offshoring-consulting': 123,
 'strategic-management-services': 102,
 'design-services': 99,
 'graphic-design': 140,
 'regenerative-design': 3256,
 'interior-design': 3126,
 'engineering-services': 3242,
 'robotics-engineering': 3248,
 'surveying-and-mapping-services': 3249,
 'it-services-and-it-consulting': 96,
 'computer-and-network-security': 118,
 'digital-accessibility-services': 3244,
 'it-system-custom-software-development': 3102,
 'it-system-data-services': 3106,
 'it-system-design-services': 1855,
 'it-system-installation-and-disposal': 3104,
 'it-system-operations-and-maintenance': 3103,
 'it-system-testing-and-evaluation': 3107,
 'it-system-training-and-support': 3105,
 'legal-services': 10,
 'alternative-dispute-resolution': 120,
 'law-practice': 9,
 'photography': 136,
 'research-services': 70,
 'biotechnology-research': 12,
 'nanotechnology-research': 114,
 'think-tanks': 130,
 'services-for-renewable-energy': 3243,
 'veterinary-services': 16,
 'technology-information-and-media': 1594,
 'media-&-telecommunications': 3133,
 'book-and-periodical-publishing': 82,
 'book-publishing': 1602,
 'newspaper-publishing': 81,
 'periodical-publishing': 1600,
 'broadcast-media-production-and-distribution': 36,
 'cable-and-satellite-programming': 1641,
 'radio-and-television-broadcasting': 1633,
 'movies-videos-and-sound': 35,
 'animation-and-post-production': 127,
 'media-production': 126,
 'movies-and-sound-recording': 1611,
 'sound-recording': 1623,
 'sheet-music-publishing': 1625,
 'telecommunications': 8,
 'satellite-telecommunications': 1649,
 'telecommunications-carriers': 1644,
 'wireless-services': 119,
 'technology-information-and-internet': 6,
 'data-infrastructure-and-analytics': 2458,
 'blockchain-services': 3134,
 'business-intelligence-platforms': 3128,
 'climate-data-and-analytics': 3252,
 'information-services': 84,
 'internet-publishing': 3132,
 'business-content': 3129,
 'online-audio-and-video-media': 113,
 'internet-news': 3124,
 'libraries': 85,
 'blogs': 3125,
 'internet-marketplace-platforms': 1285,
 'social-networking-platforms': 3127,
 'software-development': 4,
 'computer-games': 109,
 'mobile-gaming-apps': 3131,
 'computer-networking-products': 5,
 'data-security-software-products': 3130,
 'desktop-computing-software-products': 3101,
 'embedded-software-products': 3099,
 'mobile-computing-software-products': 3100,
 'utilities': 59,
 'electric-power-generation': 383,
 'fossil-fuel-electric-power-generation': 385,
 'nuclear-electric-power-generation': 386,
 'renewable-energy-power-generation': 3240,
 'biomass-electric-power-generation': 390,
 'geothermal-electric-power-generation': 389,
 'hydroelectric-power-generation': 384,
 'solar-electric-power-generation': 387,
 'wind-electric-power-generation': 2489,
 'electric-power-transmission-control-and-distribution': 382,
 'natural-gas-distribution': 397,
 'water-waste-steam-and-air-conditioning-services': 398,
 'steam-and-air-conditioning-supply': 404,
 'waste-collection': 1981,
 'waste-treatment-and-disposal': 1986,
 'water-supply-and-irrigation-systems': 400}