# Generated by Django 5.1.1 on 2024-09-14 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('legal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('detailed_descrption', models.TextField(blank=True, null=True)),
                ('problem_statement', models.JSONField(blank=True, null=True)),
                ('customer_list', models.JSONField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('details_fetched', models.BooleanField(default=False)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTriggerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggers', models.CharField(choices=[('EH', 'Engineering hiring')], default='EH', max_length=2)),
                ('message', models.TextField(blank=True, null=True)),
                ('job_filters', models.JSONField(blank=True, null=True)),
                ('default_mail_body', models.TextField(blank=True, null=True)),
                ('default_mail_subject', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.company')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_linkedin_url', models.TextField()),
                ('mail_body', models.TextField(blank=True, null=True)),
                ('mail_subject', models.TextField(blank=True, null=True)),
                ('trigger_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.companytriggersegment')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('seniority', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_backend.company')),
            ],
        ),
    ]
