# Generated by Django 5.1.1 on 2024-09-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytriggersegment',
            name='triggers',
        ),
        migrations.AddField(
            model_name='companytriggersegment',
            name='role_category',
            field=models.CharField(choices=[('SA', 'Sales'), ('MA', 'Marketing'), ('OA', 'Operations / Admin'), ('TE', 'Tech'), ('PD', 'Product / Design'), ('AL', 'All Roles')], default='AL', max_length=2),
        ),
        migrations.AddField(
            model_name='companytriggersegment',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('AE', 'Account Executive/Account Manager (AE/AM)'), ('SM', 'Sales Manager'), ('SB', 'SDR/BDR'), ('FS', 'Field Sales'), ('DM', 'Digital Marketing'), ('CS', 'Content Specialist'), ('EM', 'Email Marketing Specialist'), ('EV', 'Event Marketing'), ('CSM', 'Customer Success Manager'), ('CSP', 'Customer Support'), ('FSP', 'Field Support'), ('LO', 'Logistics'), ('LC', 'Legal and Compliance'), ('RO', 'Recruiting Operations'), ('SE', 'Software Engineering'), ('AI', 'Artificial Intelligence'), ('DO', 'Dev Ops'), ('QA', 'QA (Quality Assurance)'), ('PM', 'Product Management'), ('PGM', 'Program Management'), ('PO', 'Product Operations'), ('GD', 'Graphic Designer'), ('UID', 'UI Design')], max_length=3, null=True),
        ),
    ]
