# Generated by Django 5.1.1 on 2024-09-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_rename_job_filters_companytriggersegment_industry_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('mail_body', models.TextField(blank=True, null=True)),
                ('mail_subject', models.TextField(blank=True, null=True)),
                ('people_results', models.JSONField(blank=True, null=True)),
                ('trigger_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.companytriggersegment')),
            ],
        ),
        migrations.DeleteModel(
            name='PeopleSearchResult',
        ),
    ]
