# Generated by Django 5.1.1 on 2024-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0004_jobsearchresult_delete_peoplesearchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytriggersegment',
            name='person_job_level',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytriggersegment',
            name='person_job_role',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
