# Generated by Django 5.1.1 on 2024-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0005_companytriggersegment_person_job_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytriggersegment',
            name='default_mail_body',
        ),
        migrations.RemoveField(
            model_name='companytriggersegment',
            name='default_mail_subject',
        ),
        migrations.RemoveField(
            model_name='jobsearchresult',
            name='mail_body',
        ),
        migrations.RemoveField(
            model_name='jobsearchresult',
            name='mail_subject',
        ),
        migrations.AddField(
            model_name='companytriggersegment',
            name='additional_selling_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytriggersegment',
            name='default_mail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsearchresult',
            name='mail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
