# Generated by Django 5.1.1 on 2024-09-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0006_remove_companytriggersegment_default_mail_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytriggersegment',
            name='person_job_level',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='companytriggersegment',
            name='person_job_role',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
