# Generated by Django 5.1.1 on 2024-09-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0007_alter_companytriggersegment_person_job_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearchresult',
            name='company_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PeopleJobEmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_url', models.TextField(blank=True, null=True)),
                ('prospect_details', models.JSONField()),
                ('prospect_email', models.EmailField(max_length=254)),
                ('mail_content', models.JSONField(blank=True, null=True)),
                ('generated', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('send_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.jobsearchresult')),
                ('trigger_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.companytriggersegment')),
            ],
        ),
    ]
