# Generated by Django 5.1.1 on 2024-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0008_jobsearchresult_company_url_peoplejobemailtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplejobemailtask',
            name='prospect_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peoplejobemailtask',
            name='prospect_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peoplejobemailtask',
            name='prospect_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
