# Generated by Django 5.1.1 on 2024-09-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0009_peoplejobemailtask_prospect_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytriggersegment',
            name='last_job_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
